config/routes.rb
Rails.application.routes.draw do
  resources :billings
  resources :purchases
  resources :line_items
  resources :carts
  devise_for :accounts
  resources :categories
  resources :homes
  
  resources :products do
    collection do
      get :store
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'products#store'
  
end

app/models/ability.rb
#frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(account)
        account ||= Account.new # guest user (not logged in)
        if account.id == 1
            can :manage, :all
        end


        if account.admin?
            can :manage, Product
            can :manage, Category
        else
            can :show, Product
            can :store, Product
            can :create, Account
            can :read, Account, :id => account.id
            can :update, Account, :id => account.id
        end
    
  end 
end

app/models/account.rb
class Account < ApplicationRecord
	has_many :homes
	has_many :carts
	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/billing.rb
class Billing < ApplicationRecord
	has_one :home
	has_many :carts
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :line_items, dependent: :destroy
	belongs_to :account
	belongs_to :billing
	
	after_initialize :default_values

    

	def add_product(product)
	  current_item = line_items.find_by(product_id: product.id)
	  if current_item
	  	current_item.quantity += 1
	  else
	  	current_item = line_items.build(product_id: product.id)
	  end
	  current_item
	end	



	private
      def default_values
        self.account_id ||= @accountid
      end
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products

	validates :name, :description, presence: true
end

app/models/home.rb
class Home < ApplicationRecord
	belongs_to :purchase
	belongs_to :account
	belongs_to :billing

	validates :address, :postalcode, :country, :province, :location, :reference, presence: true
	validates :postalcode, numericality: true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  
  def self.recorrido
      list = []
      for l in LineItem.all
        for c in Cart.all
          if l.cart.id == c.id
            if c.account_id == current_account.id
              list.push l
            end
          end
        end
      end
      return list
  end

  
  
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
	has_many :line_items
	validates :name, :description, :price, :discountpercentage, :stock, :active, :image, presence: true
	validates :price, :discountpercentage, numericality: true
	before_destroy :ensure_not_referenced_by_any_line_item

	private
		def ensure_not_referenced_by_any_line_item
			unless line_items.empty?
				errors.add(:base, 'Line Items present')
				throw :abort
			
		end
	end
end

app/models/purchase.rb
class Purchase < ApplicationRecord
	has_many :homes
	validates :payment, presence: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_account!, except: [:show] 
  load_and_authorize_resource

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

    
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
    @accountid = current_account.id

  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(session[:cart_id])
    rescue ActiveRecord::RecordNotFound
      @cart = Cart.create
      session[:cart_id] = @cart.id
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.require(:cart).permit(:billing_id, :account_id)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_account!

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all.where(:account_id => current_account.id)
    
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def home_params
      params.require(:home).permit(:address, :postalcode, :country, :province, :location, :reference, :purchase_id, :account_id, :billing_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def price_calculate(product)
    if (product.discountpercentage) > 0
      percentage = ((product.price * product.discountpercentage) / 100)
      return product.price - percentage
    else
      return product.price
    end
  end

  

  def check_stock(product)
    if product.stock < 1
      return link_to 'NO STOCK', "#", class: 'btn btn-sm btn-outline-danger'
    else
      
      return link_to 'BUY', homes_path, class: 'btn btn-sm btn-outline-success'
      
    end
  end

  def check_stockk(product)
    if product.stock > 1
      return link_to 'Add to Cart', line_items_path(product_id: product), class: 'btn btn-sm btn-outline-secondary'
    end
  end

  

end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/css2?family=Sriracha&display=swap" rel="stylesheet">
    <title>DIETETICA VIDA FELIZ</title>
    
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    
    
    


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    

    <nav class="navbar fixed-top navbar-dark bg-warning">
      <%= link_to "Dietetic Store App", root_url, class: "navbar-brand" %>
      <%= render 'shared/store_menu' %>
      <%= render 'shared/user_menu' %>
    </nav>

    <div class="container" style="margin-top: 80px !important; min-height: 950px;">
      
      <%= yield %>
    </div>

    <%#= console %>
    <nav class="navbar fixed-bottom navbar-dark bg-secondary">
      
      <a class="navbar-brand"><small>&copy; 2020 - DIETETICA Y HERBORISTERIA VIDA FELIZ</small></a>
    </nav>
  </body>
</html>

app/views/shared/_store_menu.html.erb
<div class="btn-group text-center" role="group">
  <%= link_to "Store", store_products_url, class: "btn btn-secondary" %>
  <%= link_to "Products", products_url, class: "btn btn-secondary" %>
  <%= link_to "Categories", categories_url, class: "btn btn-secondary" %>
  <%= link_to "Cart", line_items_url, class: "btn btn-secondary" %>
  
</div>

app/views/shared/_user_menu.html.erb
<% if account_signed_in? %>
  <div class="dropdown">
    <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <%= current_account.email %>
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <%= link_to('Edit Profile', edit_account_registration_path, class: "dropdown-item") %>
      <%= link_to('Logout', destroy_account_session_path, method: :delete, class: "dropdown-item") %>
    </div>
  </div>
<% else %>
  <%= link_to('Login', new_account_session_path, class: "btn btn-primary") %>
<% end %>