config/routes.rb
Rails.application.routes.draw do
  resources :billings
  resources :purchases
  resources :line_items
  resources :carts
  devise_for :accounts
  resources :categories
  resources :homes
  
  resources :products do
    collection do
      get :store
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'products#store'
  
end

app/models/home.rb
class Home < ApplicationRecord
	belongs_to :purchase
	belongs_to :account
	belongs_to :billing

	validates :address, :postalcode, :country, :province, :location, :reference, presence: true
	validates :postalcode, numericality: true
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_account!

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all.where(:account_id => current_account.id)
    
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def home_params
      params.require(:home).permit(:address, :postalcode, :country, :province, :location, :reference, :purchase_id, :account_id, :billing_id)
    end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.erb
<head>
  <link href="https://fonts.googleapis.com/css2?family=Sriracha&display=swap" rel="stylesheet">
<head>
<%= form_with(model: home, local: true) do |form| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
        <% home.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" style="display: none">
    <%= form.label :billing_id %>
    <%= form.collection_select(:billing_id, Billing.all, :id, :id) %>
  </div>

  <div class="field" style="display: none">

    <%= form.label :account_id %>
    <%= form.text_field :account_id, value: current_account.id %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :postalcode %>
    <%= form.number_field :postalcode %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :province %>
    <%= form.text_field :province %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :reference %>
    <%= form.text_field :reference %>
  </div>

  <div class="field">
    <%= form.label :purchase_id %>
    <%= form.collection_select(:purchase_id, Purchase.all, :id, :payment) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<head>
  <link href="https://fonts.googleapis.com/css2?family=Sriracha&display=swap" rel="stylesheet">
<head>
<p id="notice"><%= notice %></p>

<h1>Homes</h1>




<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Postalcode</th>
      <th>Country</th>
      <th>Province</th>
      <th>Location</th>
      <th>Reference</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homes.each do |home| %>
      <tr>
        <td><%= home.account.first_name %></td>
        <td><%= home.address %></td>
        <td><%= home.postalcode %></td>
        <td><%= home.country %></td>
        <td><%= home.province %></td>
        <td><%= home.location %></td>
        <td><%= home.reference %></td>
        <td><%= link_to 'Show', home, class: 'btn btn-sm btn-outline-success' %></td>
        <td><%= link_to 'Edit', edit_home_path(home), class: 'btn btn-sm btn-outline-success' %></td>

        <td><%= link_to 'Destroy', home, class: 'btn btn-sm btn-outline-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Home', new_home_path, class: 'btn btn-sm btn-outline-success' %>
<%= link_to 'BUY', new_billing_path, class: 'btn btn-sm btn-outline-success' %>

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<head>
  <link href="https://fonts.googleapis.com/css2?family=Sriracha&display=swap" rel="stylesheet">
<head>
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @home.address %>
</p>

<p>
  <strong>Postalcode:</strong>
  <%= @home.postalcode %>
</p>

<p>
  <strong>Country:</strong>
  <%= @home.country %>
</p>

<p>
  <strong>Province:</strong>
  <%= @home.province %>
</p>

<p>
  <strong>Location:</strong>
  <%= @home.location %>
</p>

<p>
  <strong>Reference:</strong>
  <%= @home.reference %>
</p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>